# Generated by Django 4.2 on 2026-02-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
