# Generated by Django 4.2 on 2026-02-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['grade', 'roll_number']},
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'grade')},
        ),
    ]
