# Generated by Django 4.2 on 2026-02-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='image',
            field=models.ImageField(upload_to='answer_sheets/'),
        ),
    ]
