# Generated by Django 4.2 on 2026-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_change_answer_sheet_upload_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='image',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
